# Generated by Django 4.1.7 on 2023-05-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_status_alter_ticket_ticket_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('resolved', 'Resolved')], default='Open', max_length=255),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(blank=True, choices=[('inquiry', 'Inquiry'), ('product support', 'Product Support'), ('complaint', 'Complaint')], max_length=255, null=True),
        ),
    ]
